### ISSUE TITLE
Redis 密码设置遇到错误

### ISSUE THREAD

**Issue by MeowCold** [newnius/PV-Counter#1]
`
Fatal error: Uncaught exception 'Predis\Response\ServerException' with message 'NOAUTH Authentication required.' in /www/wwwroot/mengsuan/predis/src/Client.php:370 Stack trace: #0 /www/wwwroot/mengsuan/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\KeyExists), Object(Predis\Response\Error)) #1 /www/wwwroot/mengsuan/predis/src/Client.php(315): Predis\Client->executeCommand(Object(Predis\Command\KeyExists)) #2 /www/wwwroot/mengsuan/util4p/ReSession.class.php(30): Predis\Client->__call('exists', Array) #3 /www/wwwroot/mengsuan/util4p/ReSession.class.php(30): Predis\Client->exists('session:SukMF3i...') #4 /www/wwwroot/mengsuan/init.inc.php(50): Session::configure(Object(CRObject)) #5 /www/wwwroot/mengsuan/init.inc.php(16): init_Session() #6 /www/wwwroot/mengsuan/install.php(8): require_once('/www/wwwroot/me...') #7 {main} thrown in /www/wwwroot/mengsuan/predis/src/Client.php on line 370
`
配置：
![20190117225228](https://user-images.githubusercontent.com/7279597/51326714-b9792e80-1aaa-11e9-8860-08d07ce01ccb.png)
引擎	Redis-2.8

**Comment by newnius** [comment]
你好，应该是因为你的 Redis 设置了密码，程序默认redis是不设置密码的。

不太建议给redis 设置密码，因为redis没有做频率控制，而且redis速度很快，爆破的时间可以做到很短。设置密码反而影响了速度。

一个比较好的安全措施是让redis仅监听本地ip，即 `127.0.0.1`

你可以参考 [Redis配置详解](https://blog.csdn.net/thinkercode/article/details/46580871) ，把 `bind` 项改成 `bind 127.0.0.1`，并注释 `requirepass`这一项，随后重启redis

**Comment by newnius** [comment]
如果一定需要连接带密码的redis，需要修改源码

在[util4p/RedisDAO.class.php#L29](https://github.com/newnius/PV-Counter/blob/cb8d6cf6233bfa87a6bab2b321124cf47c244c3b/util4p/RedisDAO.class.php#L29)加上这一项
```
'parameters'=>[
'password' => 'DpxWMgwkQnf9CNIi'
]
```

参考[请问怎么带密码建立Redis连接？](https://github.com/nrk/predis/issues/506)

**Comment by newnius** [comment]
另，如果想要在非本地环境下部署，需要配置 `OAUTH_CLIENT_ID` 和 `OAUTH_CLIENT_SECRET`
 
在 [QuickAuth](https://quickauth.newnius.com/) -> Sites 菜单下添加站点，然后获得 `ClientID`与`ClientSecret`

**Comment by MeowCold** [comment]
感谢，腾讯云	Redis 默认要求必须设置密码

**Comment by MeowCold** [comment]
能不能不带OAuth？只是自用

**Comment by newnius** [comment]
因为不想再重新写一套账号系统，所以用的OAuth，可以自己加一个简单的验证页面，只需要完成 [auth.php#L68](https://github.com/newnius/PV-Counter/blob/cb8d6cf6233bfa87a6bab2b321124cf47c244c3b/auth.php#L68) 这一部分的代码实现即可。role 为 root 或 admin 均可。

一般来说，配置完成之后，系统就可以正常运行了，只有当需要配置自定义模式时（默认会将 view.php?id=x 类型的网页识别成一个网页，即忽略参数），才会用到后台管理。

**Comment by MeowCold** [comment]
原来这样 谢谢 谢谢解答

**Comment by MeowCold** [comment]
![1](https://user-images.githubusercontent.com/7279597/51332485-cb60ce80-1ab6-11e9-992b-d10ab5ea2696.png)
报错：
`Fatal error: Uncaught exception 'Predis\Response\ServerException' with message 'NOAUTH Authentication required.' in /www/wwwroot/mengsuan/predis/src/Client.php:370 Stack trace: #0 /www/wwwroot/mengsuan/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\KeyExists), Object(Predis\Response\Error)) #1 /www/wwwroot/mengsuan/predis/src/Client.php(315): Predis\Client->executeCommand(Object(Predis\Command\KeyExists)) #2 /www/wwwroot/mengsuan/util4p/ReSession.class.php(30): Predis\Client->__call('exists', Array) #3 /www/wwwroot/mengsuan/util4p/ReSession.class.php(30): Predis\Client->exists('session:53eQnhs...') #4 /www/wwwroot/mengsuan/init.inc.php(50): Session::configure(Object(CRObject)) #5 /www/wwwroot/mengsuan/init.inc.php(16): init_Session() #6 /www/wwwroot/mengsuan/install.php(8): require_once('/www/wwwroot/me...') #7 {main} thrown in /www/wwwroot/mengsuan/predis/src/Client.php on line 370`

![2](https://user-images.githubusercontent.com/7279597/51332609-019e4e00-1ab7-11e9-98b3-84b58498bc9b.png)
报错：
`Parse error: syntax error, unexpected ''parameters'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /www/wwwroot/mengsuan/util4p/RedisDAO.class.php on line 33`

我看了你给的参考依旧没解决233
不知道我是不是忽略了哪里OXO

**Comment by newnius** [comment]
抱歉，没有仔细做过验证。

可能是相应的issue版本不一样，当前的做法只需添加一项 password 即可，不需要包裹在parameters参数中。

文档参见 [Quick tour](https://github.com/nrk/predis/wiki/Quick-tour#connection)

**Comment by MeowCold** [comment]
![11](https://user-images.githubusercontent.com/7279597/51374888-51285c80-1b3f-11e9-8f79-1d9b1db9b74c.png)

tatic/config.js 也改了
但
报错：
![tim 20190118162355](https://user-images.githubusercontent.com/7279597/51374944-76b56600-1b3f-11e9-9704-0904604cb7f1.png)
![tim 20190118162314](https://user-images.githubusercontent.com/7279597/51374952-7ddc7400-1b3f-11e9-931e-0310794bc94c.png)

Sign in 无效
Help 无效
help 从控制台看
`<a href="http://127.0.0.1/help">Help</a>`
改了/config.inc.php
`define('BASE_URL', 'https://mengsuan.mwulu.com'); `
但访问依旧
https://mengsuan.mwulu.com/help
除非
https://mengsuan.mwulu.com/help.php

感觉自己好渣

**Comment by newnius** [comment]
你好，你的链接我看了一下，127.0.0.1应该是浏览器缓存没生效，现在可以了。

另外，页面提示404，是因为你的apache没有启用 伪静态，rewrite模块

https://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2

**Comment by MeowCold** [comment]
我使用的是Nginx，不知道我这个伪静态对吗？看着能用的样子
![tim 20190119005612](https://user-images.githubusercontent.com/7279597/51401144-09c4bf00-1b85-11e9-9fdf-ad536bf85c4b.png)


清空浏览器缓存正常了
另外发现登陆时授权有点问题
![tim 20190119005106](https://user-images.githubusercontent.com/7279597/51401030-ca966e00-1b84-11e9-82f0-09045c1a3ac1.png)
![tim 20190119005138](https://user-images.githubusercontent.com/7279597/51401041-cff3b880-1b84-11e9-9a12-4450e1eecaec.png)
还是127.0.0.1  郁闷

**Comment by newnius** [comment]
伪静态设置应该对了。

OAuth 登陆，需要申请自己的 ClientID 和 ClientSecret 的，申请链接上面的评论里有。

**Comment by MeowCold** [comment]
我是申请并设置好了的，但它对网址显示成了127.0.0.1

**Comment by newnius** [comment]
看了一下，你没有修改 `OAUTH_CLIENT_ID` 跟 `OAUTH_CLIENT_SECRET` 吧，还是用的默认的
